set(APPLICATION_DESCRIPTION "A private-first Material phone and messaging client")
set(APPLICATION_ID "com.dingdingprojects.materialphone")
set(APPLICATION_NAME "Material Phone")
set(APPLICATION_URL "https://github.com/Ding-Ding-Projects/material-phone")
set(APPLICATION_VENDOR "Ding Ding Projects")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2010")
set(APPLICATION_SEMVER ${LINPHONEAPP_VERSION})

set(EXECUTABLE_NAME ${LINPHONEAPP_EXECUTABLE_NAME})
