if(NOT DEFINED REPOSITORY_ROOT)
    get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
endif()

function(require_line file pattern description)
    file(STRINGS "${file}" lines)
    set(found FALSE)
    foreach(line IN LISTS lines)
        if(line MATCHES "${pattern}")
            set(found TRUE)
            break()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "Production PBX wiring contract missing: ${description} (${file})")
    endif()
endfunction()

set(root_cmake "${REPOSITORY_ROOT}/CMakeLists.txt")
set(app_cmake "${REPOSITORY_ROOT}/Linphone/CMakeLists.txt")
set(model_cmake "${REPOSITORY_ROOT}/Linphone/model/CMakeLists.txt")
set(app_cpp "${REPOSITORY_ROOT}/Linphone/core/App.cpp")
set(service_cpp "${REPOSITORY_ROOT}/Linphone/model/pbx/PbxService.cpp")

foreach(required_file IN ITEMS "${root_cmake}" "${app_cmake}" "${model_cmake}" "${app_cpp}" "${service_cpp}")
    if(NOT EXISTS "${required_file}")
        message(FATAL_ERROR "Production PBX wiring contract missing file: ${required_file}")
    endif()
endforeach()

file(STRINGS "${root_cmake}" root_lines)
set(provider_position -1)
set(app_position -1)
set(line_number 0)
foreach(line IN LISTS root_lines)
    math(EXPR line_number "${line_number} + 1")
    if(line MATCHES "^[ \t]*add_subdirectory[(]\"Linphone/pbx\"[)][ \t]*$")
        set(provider_position ${line_number})
    elseif(line MATCHES "^[ \t]*add_linphone_app[(][)][ \t]*$")
        set(app_position ${line_number})
    endif()
endforeach()
if(provider_position LESS 0 OR app_position LESS 0 OR NOT provider_position LESS app_position)
    message(FATAL_ERROR "Production PBX wiring contract missing: provider target must exist before the desktop target")
endif()

if(NOT CMAKE_SCRIPT_MODE_FILE)
    if(NOT TARGET material_phone_pbx OR NOT TARGET Linphone)
        message(FATAL_ERROR "Production PBX wiring contract missing: configured provider or desktop target")
    endif()
endif()

require_line("${model_cmake}" "^[ \t]*model/pbx/PbxService[.]cpp[ \t]*$" "service source registration")
require_line("${app_cmake}" "^[ \t]*target_link_libraries[(][$][{]TARGET_NAME[}][ \t]+PRIVATE[ \t]+material_phone_pbx[)][ \t]*$" "desktop target link")
require_line("${app_cmake}" "^[ \t]*target_compile_definitions[(][$][{]TARGET_NAME[}][ \t]+PRIVATE[ \t]+HAVE_MATERIAL_PHONE_PBX_PROVIDER=1[)][ \t]*$" "QML exposure compile definition")
require_line("${app_cpp}" "^#include[ \t]+\"model/pbx/PbxService[.]hpp\"[ \t]*$" "service include")
require_line("${app_cpp}" "^[ \t]*qmlRegisterSingletonType<PbxService>[(][ \t]*$" "QML singleton exposure")
require_line("${service_cpp}" "^[ \t]*pbx::SimulatorPbxProviderFactory[ \t]+factory;[ \t]*$" "explicit simulator factory")
require_line("${service_cpp}" "^[ \t]*workerState->provider[ \t]*=[ \t]*factory[.]create[(][)][;][ \t]*$" "public provider factory call")
require_line("${service_cpp}" "^[ \t]*auto[ \t]+opened[ \t]*=[ \t]*workerState->provider->open_session[(]options,[ \t]*context[)][;][ \t]*$" "owned session open")
require_line("${service_cpp}" "^[ \t]*QTimer::singleShot[(]0,[ \t]*this,[ \t]*&PbxService::refresh[)][;][ \t]*$" "bounded initial refresh")
require_line("${service_cpp}" "^[ \t]*auto[ \t]+future[ \t]*=[ \t]*QtConcurrent::run[(]" "non-blocking refresh")
require_line("${service_cpp}" "^[ \t]*if[ \t]*[(]mBusy[)][ \t]+mCancellation[.]cancel[(][)][;][ \t]*$" "cancellation path")

message(STATUS "Production PBX wiring contract verified")
